# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 781, 609))
        self.gridLayoutWidget.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.B41 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B41.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B41.setFont(font)
        self.B41.setObjectName("B41")
        self.gridLayout_3.addWidget(self.B41, 1, 1, 1, 1)
        self.B40 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B40.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B40.setFont(font)
        self.B40.setObjectName("B40")
        self.gridLayout_3.addWidget(self.B40, 0, 1, 1, 1)
        self.B50 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B50.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B50.setFont(font)
        self.B50.setObjectName("B50")
        self.gridLayout_3.addWidget(self.B50, 0, 2, 1, 1)
        self.B31 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B31.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B31.setFont(font)
        self.B31.setObjectName("B31")
        self.gridLayout_3.addWidget(self.B31, 1, 0, 1, 1)
        self.B42 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B42.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B42.setFont(font)
        self.B42.setObjectName("B42")
        self.gridLayout_3.addWidget(self.B42, 2, 1, 1, 1)
        self.B30 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B30.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B30.setFont(font)
        self.B30.setObjectName("B30")
        self.gridLayout_3.addWidget(self.B30, 0, 0, 1, 1)
        self.B32 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B32.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B32.setFont(font)
        self.B32.setObjectName("B32")
        self.gridLayout_3.addWidget(self.B32, 2, 0, 1, 1)
        self.B51 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B51.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B51.setFont(font)
        self.B51.setObjectName("B51")
        self.gridLayout_3.addWidget(self.B51, 1, 2, 1, 1)
        self.B52 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B52.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B52.setFont(font)
        self.B52.setObjectName("B52")
        self.gridLayout_3.addWidget(self.B52, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.B14 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B14.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B14.setFont(font)
        self.B14.setObjectName("B14")
        self.gridLayout_5.addWidget(self.B14, 1, 1, 1, 1)
        self.B13 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B13.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B13.setFont(font)
        self.B13.setObjectName("B13")
        self.gridLayout_5.addWidget(self.B13, 0, 1, 1, 1)
        self.B23 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B23.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B23.setFont(font)
        self.B23.setObjectName("B23")
        self.gridLayout_5.addWidget(self.B23, 0, 2, 1, 1)
        self.B04 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B04.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B04.setFont(font)
        self.B04.setObjectName("B04")
        self.gridLayout_5.addWidget(self.B04, 1, 0, 1, 1)
        self.B15 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B15.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B15.setFont(font)
        self.B15.setObjectName("B15")
        self.gridLayout_5.addWidget(self.B15, 2, 1, 1, 1)
        self.B03 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B03.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B03.setFont(font)
        self.B03.setObjectName("B03")
        self.gridLayout_5.addWidget(self.B03, 0, 0, 1, 1)
        self.B05 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B05.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B05.setFont(font)
        self.B05.setObjectName("B05")
        self.gridLayout_5.addWidget(self.B05, 2, 0, 1, 1)
        self.B24 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B24.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B24.setFont(font)
        self.B24.setObjectName("B24")
        self.gridLayout_5.addWidget(self.B24, 1, 2, 1, 1)
        self.B25 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B25.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B25.setFont(font)
        self.B25.setObjectName("B25")
        self.gridLayout_5.addWidget(self.B25, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.B20 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B20.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B20.setFont(font)
        self.B20.setObjectName("B20")
        self.gridLayout_4.addWidget(self.B20, 0, 2, 1, 1)
        self.B01 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B01.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B01.setFont(font)
        self.B01.setObjectName("B01")
        self.gridLayout_4.addWidget(self.B01, 1, 0, 1, 1)
        self.B00 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B00.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B00.setFont(font)
        self.B00.setObjectName("B00")
        self.gridLayout_4.addWidget(self.B00, 0, 0, 1, 1)
        self.B02 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B02.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B02.setFont(font)
        self.B02.setObjectName("B02")
        self.gridLayout_4.addWidget(self.B02, 2, 0, 1, 1)
        self.B11 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B11.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B11.setFont(font)
        self.B11.setObjectName("B11")
        self.gridLayout_4.addWidget(self.B11, 1, 1, 1, 1)
        self.B10 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B10.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B10.setFont(font)
        self.B10.setObjectName("B10")
        self.gridLayout_4.addWidget(self.B10, 0, 1, 1, 1)
        self.B21 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B21.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B21.setFont(font)
        self.B21.setObjectName("B21")
        self.gridLayout_4.addWidget(self.B21, 1, 2, 1, 1)
        self.B12 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B12.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B12.setFont(font)
        self.B12.setObjectName("B12")
        self.gridLayout_4.addWidget(self.B12, 2, 1, 1, 1)
        self.B22 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B22.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B22.setFont(font)
        self.B22.setObjectName("B22")
        self.gridLayout_4.addWidget(self.B22, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_10.setFont(font)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_10.setLineWidth(5)
        self.line_10.setMidLineWidth(5)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 4, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_11.setFont(font)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_11.setLineWidth(5)
        self.line_11.setMidLineWidth(5)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 2, 3, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_12.setFont(font)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_12.setLineWidth(5)
        self.line_12.setMidLineWidth(5)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 0, 3, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.B17 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B17.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B17.setFont(font)
        self.B17.setObjectName("B17")
        self.gridLayout_7.addWidget(self.B17, 1, 1, 1, 1)
        self.B16 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B16.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B16.setFont(font)
        self.B16.setObjectName("B16")
        self.gridLayout_7.addWidget(self.B16, 0, 1, 1, 1)
        self.B26 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B26.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B26.setFont(font)
        self.B26.setObjectName("B26")
        self.gridLayout_7.addWidget(self.B26, 0, 2, 1, 1)
        self.B07 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B07.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B07.setFont(font)
        self.B07.setObjectName("B07")
        self.gridLayout_7.addWidget(self.B07, 1, 0, 1, 1)
        self.B18 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B18.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B18.setFont(font)
        self.B18.setObjectName("B18")
        self.gridLayout_7.addWidget(self.B18, 2, 1, 1, 1)
        self.B06 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B06.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B06.setFont(font)
        self.B06.setObjectName("B06")
        self.gridLayout_7.addWidget(self.B06, 0, 0, 1, 1)
        self.B08 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B08.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B08.setFont(font)
        self.B08.setObjectName("B08")
        self.gridLayout_7.addWidget(self.B08, 2, 0, 1, 1)
        self.B27 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B27.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B27.setFont(font)
        self.B27.setObjectName("B27")
        self.gridLayout_7.addWidget(self.B27, 1, 2, 1, 1)
        self.B28 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B28.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B28.setFont(font)
        self.B28.setObjectName("B28")
        self.gridLayout_7.addWidget(self.B28, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_4.setFont(font)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_4.setLineWidth(5)
        self.line_4.setMidLineWidth(5)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_5.setFont(font)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_5.setLineWidth(5)
        self.line_5.setMidLineWidth(5)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 2, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_6.setFont(font)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_6.setLineWidth(5)
        self.line_6.setMidLineWidth(5)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 3, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_2.setFont(font)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(5)
        self.line_2.setMidLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_3.setFont(font)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(5)
        self.line_3.setMidLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 4, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_8.setFont(font)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_8.setLineWidth(5)
        self.line_8.setMidLineWidth(5)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 0, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_7.setFont(font)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_7.setLineWidth(5)
        self.line_7.setMidLineWidth(5)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 2, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_9.setFont(font)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_9.setLineWidth(5)
        self.line_9.setMidLineWidth(5)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 4, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.B44 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B44.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B44.setFont(font)
        self.B44.setObjectName("B44")
        self.gridLayout_6.addWidget(self.B44, 1, 1, 1, 1)
        self.B43 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B43.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B43.setFont(font)
        self.B43.setObjectName("B43")
        self.gridLayout_6.addWidget(self.B43, 0, 1, 1, 1)
        self.B53 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B53.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B53.setFont(font)
        self.B53.setObjectName("B53")
        self.gridLayout_6.addWidget(self.B53, 0, 2, 1, 1)
        self.B34 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B34.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B34.setFont(font)
        self.B34.setObjectName("B34")
        self.gridLayout_6.addWidget(self.B34, 1, 0, 1, 1)
        self.B45 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B45.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B45.setFont(font)
        self.B45.setObjectName("B45")
        self.gridLayout_6.addWidget(self.B45, 2, 1, 1, 1)
        self.B33 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B33.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B33.setFont(font)
        self.B33.setObjectName("B33")
        self.gridLayout_6.addWidget(self.B33, 0, 0, 1, 1)
        self.B35 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B35.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B35.setFont(font)
        self.B35.setObjectName("B35")
        self.gridLayout_6.addWidget(self.B35, 2, 0, 1, 1)
        self.B54 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B54.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B54.setFont(font)
        self.B54.setObjectName("B54")
        self.gridLayout_6.addWidget(self.B54, 1, 2, 1, 1)
        self.B55 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B55.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B55.setFont(font)
        self.B55.setObjectName("B55")
        self.gridLayout_6.addWidget(self.B55, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 2, 2, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.B77 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B77.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B77.setFont(font)
        self.B77.setObjectName("B77")
        self.gridLayout_9.addWidget(self.B77, 1, 1, 1, 1)
        self.B76 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B76.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B76.setFont(font)
        self.B76.setObjectName("B76")
        self.gridLayout_9.addWidget(self.B76, 0, 1, 1, 1)
        self.B86 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B86.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B86.setFont(font)
        self.B86.setObjectName("B86")
        self.gridLayout_9.addWidget(self.B86, 0, 2, 1, 1)
        self.B67 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B67.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B67.setFont(font)
        self.B67.setObjectName("B67")
        self.gridLayout_9.addWidget(self.B67, 1, 0, 1, 1)
        self.B78 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B78.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B78.setFont(font)
        self.B78.setObjectName("B78")
        self.gridLayout_9.addWidget(self.B78, 2, 1, 1, 1)
        self.B66 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B66.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B66.setFont(font)
        self.B66.setObjectName("B66")
        self.gridLayout_9.addWidget(self.B66, 0, 0, 1, 1)
        self.B68 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B68.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B68.setFont(font)
        self.B68.setObjectName("B68")
        self.gridLayout_9.addWidget(self.B68, 2, 0, 1, 1)
        self.B87 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B87.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B87.setFont(font)
        self.B87.setObjectName("B87")
        self.gridLayout_9.addWidget(self.B87, 1, 2, 1, 1)
        self.B88 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B88.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B88.setFont(font)
        self.B88.setObjectName("B88")
        self.gridLayout_9.addWidget(self.B88, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 4, 4, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.B71 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B71.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B71.setFont(font)
        self.B71.setObjectName("B71")
        self.gridLayout_11.addWidget(self.B71, 1, 1, 1, 1)
        self.B70 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B70.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B70.setFont(font)
        self.B70.setObjectName("B70")
        self.gridLayout_11.addWidget(self.B70, 0, 1, 1, 1)
        self.B80 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B80.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B80.setFont(font)
        self.B80.setObjectName("B80")
        self.gridLayout_11.addWidget(self.B80, 0, 2, 1, 1)
        self.B61 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B61.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B61.setFont(font)
        self.B61.setObjectName("B61")
        self.gridLayout_11.addWidget(self.B61, 1, 0, 1, 1)
        self.B72 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B72.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B72.setFont(font)
        self.B72.setObjectName("B72")
        self.gridLayout_11.addWidget(self.B72, 2, 1, 1, 1)
        self.B60 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B60.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B60.setFont(font)
        self.B60.setObjectName("B60")
        self.gridLayout_11.addWidget(self.B60, 0, 0, 1, 1)
        self.B62 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B62.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B62.setFont(font)
        self.B62.setObjectName("B62")
        self.gridLayout_11.addWidget(self.B62, 2, 0, 1, 1)
        self.B81 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B81.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B81.setFont(font)
        self.B81.setObjectName("B81")
        self.gridLayout_11.addWidget(self.B81, 1, 2, 1, 1)
        self.B82 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B82.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B82.setFont(font)
        self.B82.setObjectName("B82")
        self.gridLayout_11.addWidget(self.B82, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_11, 0, 4, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.B47 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B47.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B47.setFont(font)
        self.B47.setObjectName("B47")
        self.gridLayout_8.addWidget(self.B47, 1, 1, 1, 1)
        self.B46 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B46.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B46.setFont(font)
        self.B46.setObjectName("B46")
        self.gridLayout_8.addWidget(self.B46, 0, 1, 1, 1)
        self.B56 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B56.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B56.setFont(font)
        self.B56.setObjectName("B56")
        self.gridLayout_8.addWidget(self.B56, 0, 2, 1, 1)
        self.B37 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B37.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B37.setFont(font)
        self.B37.setObjectName("B37")
        self.gridLayout_8.addWidget(self.B37, 1, 0, 1, 1)
        self.B48 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B48.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B48.setFont(font)
        self.B48.setObjectName("B48")
        self.gridLayout_8.addWidget(self.B48, 2, 1, 1, 1)
        self.B36 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B36.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B36.setFont(font)
        self.B36.setObjectName("B36")
        self.gridLayout_8.addWidget(self.B36, 0, 0, 1, 1)
        self.B38 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B38.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B38.setFont(font)
        self.B38.setObjectName("B38")
        self.gridLayout_8.addWidget(self.B38, 2, 0, 1, 1)
        self.B57 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B57.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B57.setFont(font)
        self.B57.setObjectName("B57")
        self.gridLayout_8.addWidget(self.B57, 1, 2, 1, 1)
        self.B58 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B58.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B58.setFont(font)
        self.B58.setObjectName("B58")
        self.gridLayout_8.addWidget(self.B58, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 4, 2, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.B74 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B74.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B74.setFont(font)
        self.B74.setObjectName("B74")
        self.gridLayout_10.addWidget(self.B74, 1, 1, 1, 1)
        self.B73 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B73.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B73.setFont(font)
        self.B73.setObjectName("B73")
        self.gridLayout_10.addWidget(self.B73, 0, 1, 1, 1)
        self.B83 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B83.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B83.setFont(font)
        self.B83.setObjectName("B83")
        self.gridLayout_10.addWidget(self.B83, 0, 2, 1, 1)
        self.B64 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B64.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B64.setFont(font)
        self.B64.setObjectName("B64")
        self.gridLayout_10.addWidget(self.B64, 1, 0, 1, 1)
        self.B75 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B75.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B75.setFont(font)
        self.B75.setObjectName("B75")
        self.gridLayout_10.addWidget(self.B75, 2, 1, 1, 1)
        self.B63 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B63.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B63.setFont(font)
        self.B63.setObjectName("B63")
        self.gridLayout_10.addWidget(self.B63, 0, 0, 1, 1)
        self.B65 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B65.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B65.setFont(font)
        self.B65.setObjectName("B65")
        self.gridLayout_10.addWidget(self.B65, 2, 0, 1, 1)
        self.B84 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B84.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B84.setFont(font)
        self.B84.setObjectName("B84")
        self.gridLayout_10.addWidget(self.B84, 1, 2, 1, 1)
        self.B85 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B85.setMinimumSize(QtCore.QSize(20, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.B85.setFont(font)
        self.B85.setObjectName("B85")
        self.gridLayout_10.addWidget(self.B85, 2, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_10, 2, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Give Solution"))
        self.pushButton.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

